### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Paril** [sashi0034/angel-lsp#64]
I think I discovered what's happening with the crashes. It's gotten worse the larger my AS project has gotten, and I turned on tracing just out of curiosity;

```
[Trace - 4:09:02 AM] Sending request 'textDocument/definition - (163)'.
[Trace - 4:09:02 AM] Sending notification 'textDocument/didChange'.
[Trace - 4:09:02 AM] Sending notification '$/cancelRequest'.
[Trace - 4:09:02 AM] Sending request 'textDocument/definition - (164)'.

<--- Last few GCs --->

[61028:00006F8800114000]   120796 ms: Scavenge 4052.3 (4073.9) -> 4051.5 (4074.2) MB, pooled: 2 MB, 4.04 / 0.00 ms  (average mu = 0.065, current mu = 0.037) allocation failure; 
[61028:00006F8800114000]   124521 ms: Mark-Compact 4052.6 (4074.2) -> 4051.6 (4078.7) MB, pooled: 0 MB, 3721.14 / 0.00 ms  (average mu = 0.367, current mu = 0.435) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF79E4FEB5A uv_cpumask_size+56202
 2: 00007FF79E47864B node::OnFatalError+747
 3: 00007FF7A15E90D4 v8::Function::NewInstance+868
 4: 00007FF7A15E9043 v8::Function::NewInstance+723
 5: 00007FF7A16B9D67 v8::CppHeap::CollectGarbageInYoungGenerationForTesting+66807
 6: 00007FF79D0C5104 v8::CppHeap::Terminate+134340
 7: 00007FF79D0C487B v8::CppHeap::Terminate+132155
 8: 00007FF7A0A6C75D Cr_z_adler32+5491917
 9: 00007FF79FCDC444 v8::internal::ThreadIsolation::StartOfJitAllocationAt+348100
10: 00007FF79FCD7912 v8::internal::ThreadIsolation::StartOfJitAllocationAt+328850
11: 00007FF79FCC7836 v8::internal::ThreadIsolation::StartOfJitAllocationAt+263094
12: 00007FF79FA8FF46 uv_random+3635446
13: 00007FF79FCCFB7E v8::internal::ThreadIsolation::StartOfJitAllocationAt+296702
14: 00007FF79FDF91F2 v8::internal::StrongRootAllocatorBase::deallocate_impl+1151410
15: 00007FF79FDE5907 v8::internal::StrongRootAllocatorBase::deallocate_impl+1071303
16: 00007FF7A00CB432 v8::internal::compiler::CompilationDependencies::Commit+402
17: 00007FF7A0134648 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+425128
18: 00007FF79D049BFD v8::internal::OptimizingCompileDispatcherQueue::Enqueue+27965
19: 00007FF79FC879AE v8::internal::ThreadIsolation::StartOfJitAllocationAt+1326
20: 00007FF79FCAEB5D v8::internal::ThreadIsolation::StartOfJitAllocationAt+161501
21: 00007FF79FF30831 v8::internal::StrongRootAllocatorBase::deallocate_impl+2426865
22: 00007FF7A0393E3A v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2913434
23: 00007FF7A02F3D58 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2257848
24: 00007FF7E0195C00 
[Error - 4:09:02 AM] Server process exited with code 134.
[Info  - 4:09:02 AM] Connection to server got closed. Server will restart.
true
[Trace - 4:09:02 AM] Sending request 'initialize - (0)'.
[Trace - 4:09:02 AM] Received response 'initialize - (0)' in 149ms.
[Trace - 4:09:02 AM] Sending notification 'initialized'.
[Trace - 4:09:02 AM] Sending notification 'textDocument/didOpen'.
```

Not sure exactly what other info I can provide for this one, though.

**Comment by Paril** [comment]
Secondarily, I noticed that the langserv seems to start processing immediately on every character you type; it causes the CPU usage to jump insanely high while typing. Memory usage just keeps going up as well, so there's def something going on.

I can provide a zip of the project if you want to try to repro with it, although I'd rather send it by email since I don't want it public just yet.

**Comment by sashi0034** [comment]
Thank you for the report.
Your sharing the project will be helpful for this as well as other issues, thanks! I’ve already sent you an email on your profile, so please check it.

**Comment by SpazElectro** [comment]
Hi! I'm also getting this issue, here are my project files:
[include.zip](https://github.com/user-attachments/files/18546360/include.zip)
The node process of the extension sometimes reaches ~1GB of memory usage

**Comment by sashi0034** [comment]
Thanks, I'll check it later.

**Comment by Paril** [comment]
I'm hoping to track this down more in-depth tonight, but I think I narrowed it down - it seems to have to do with the way inspection results are stored. From digging around a bit, here's what I think is happening:

- Have multiple files with inclusions (or use mutual inclusion mode)
- Each file processes itself, and produces an AnalyzedScope
- Each file references the AnalyzedScope of included files
- After the file gets analyzed, it then loops over all files that include this file (which, with mutual inclusion mode, is *every time*) and re-analyzes them inline
- The `s_inspectedResults` value is replaced with a brand new Analyzed scope, but all of the other files are still referencing the old ones, leaving those references hanging
- The more files you have, the more it exponentially grows until blowing up

So there's two main issues that I can see here:
- the result object is overwritten even though other results are holding references to it, so it can't properly free this memory
- inspectFile directly calls reanalyzeFilesWithDependency, which is exponentially increasing the number of parses since include files don't need to be parsed during inspectAllFilesUnderDirectory. I'm not sure offhand how to fix this, but I suspect we'll need to have dependencies of files pulled out after an inspection, and let the caller decide what to do with them (`inspectAllFilesUnderDirectory` can probably ignore them, but `onDidChangeContent` might need to do something with them - the other issue is this will cause a loop because of circular dependencies if it's just done naively).

**Comment by Paril** [comment]
https://github.com/Paril/angel-lsp/tree/paril/fix-cpu-warmer

I have some temporary fixes in here - annoyingly most of my time is being spent fighting weird decisions (URIs encoded with `%3A` instead of `:` for drive names despite every API in existence not doing that, randomized ports for debuggers being standard so I always have to add a different port to get the memory debugging tools, etc). This branch currently just fixes the exponential loop, and I have an attempt at fixing the dangling reference problem but I've not narrowed down the exact cause yet. It also fixes subfolders not working properly.

The bulk of the leaked memory is `Map` and `Array`; the `Map` leaks seem to be mostly stored in `symbolMap`. `Array` is `tokenizedTokens`. My project is just so large, though, that re-inspecting any file will grow the memory usage by 200 MB. Even worse is there's no delay for document change events, so simply typing a word like "hello" will re-inspect the same file 5 times immediately.

Not having distinct classes is also making it difficult since every object is just grouped under Object. I suspect these are all SymbolScopes, and the issue is that every analysis wipes the old fullScope, but other parts of the code are still holding onto the scope from a SymbolMap somewhere or something.

**Comment by sashi0034** [comment]
Thank you very much for your hard work! It looks very informative. I just now have some time to work on it and I will get to it.

**Comment by Paril** [comment]
No problem! I wish I had more time too, but hopefully any analysis I can post here helps. The next thing I was going to look into was the diagnostics, to make sure that scopes aren't being held onto longer than they need to.

**Comment by sashi0034** [comment]
For now, I decided to avoid the memory leak by deleting all caches, thereby triggering GC (This is done in the PR above)
However, I looked at the code for a few hours and could not find the root cause. This is harder than I thought... I wonder if there is a circular reference that is causing a memory leak that I didn't intend.
I have some time this month and next month, so I'll try to find the cause of this memory leak along with other bugs as I go along.

**Comment by Paril** [comment]
Yeah I haven't been able to track down who is exactly holding onto the scope. Chrome devtools are the best in class but they are nigh impossible to read when hunting for leaks. The best I can find right now is that `SymbolScope` is the root object that somebody is holding a reference to.

One thing I can think of is to remove any usage of SymbolScope or SymbolObject stored in any structs and instead indirectly store the path to fetch that symbol, like as an array of strings or something (eg `[ "file.as", "some_namespace", "func_scope" ]`). I'm not too familiar with how all of the different interfaces/types interact in this langserv though, but in theory this would ensure nobody outside of the global `s_inspectedResults` is holding scopes, and would make it possible to detect accidentally-stale results (if a scope path can't be fetched, chances are its view of the file is out of date).

I also recommend replacing loose interfaces constructed as objects with actual classes, just to make it easier to hunt via the devtools since classes are named whereas objects are not.

**Comment by sashi0034** [comment]
I see, thank you for the very useful information!
I will try to refactor the project in the future to incorporate those revisions.

**Comment by Paril** [comment]
> For now, I decided to avoid the memory leak by deleting all caches occasionally, thereby triggering GC (This is done in the PR above) However, I looked at the code for a few hours and could not find the root cause. This is harder than I thought... I wonder if there is a circular reference that is causing a memory leak that I didn't intend. I have some time this month and next month, so I'll try to find the cause of this memory leak along with other bugs as I go along.

For the most part, this is actually working - it no longer out of memory crashes - however, it still gets stuck in an infinite loop after editing files for a few times. I suspect it's an issue with "implicit include" and the way it includes other files getting stuck continuously including the same files over and over again. I can't really confirm this ATM though.

**Comment by Paril** [comment]
Hoping to catch a trace in verbose mode, but I captured a trace in messages mode for now; not sure if it helps narrow things down though, but you can see when the server stopped receiving messages.

```

[Trace - 8:00:15 PM] Sending request 'textDocument/diagnostic - (15623)'.
🔬 Inspect "file:///g%3A/kex/quake2ex/kex3_ptah/source/game/as/scripts/game/ctf.as"
[Trace - 8:00:15 PM] Sending request 'textDocument/completion - (15624)'.
[Trace - 8:00:15 PM] Received request 'workspace/diagnostic/refresh - (4072)'.
[Trace - 8:00:15 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:15 PM] Sending response 'workspace/diagnostic/refresh - (4072)'. Processing request took 0ms
[Trace - 8:00:15 PM] Sending request 'textDocument/diagnostic - (15625)'.
[Trace - 8:00:15 PM] Sending request 'textDocument/diagnostic - (15626)'.
[Trace - 8:00:15 PM] Received response 'textDocument/diagnostic - (15623)' in 18ms.
[Trace - 8:00:15 PM] Sending request 'textDocument/diagnostic - (15627)'.
[Trace - 8:00:15 PM] Received response 'textDocument/completion - (15624)' in 17ms.
[Trace - 8:00:15 PM] Received response 'textDocument/diagnostic - (15625)' in 2ms.
[Trace - 8:00:15 PM] Received response 'textDocument/diagnostic - (15626)' in 2ms.
[Trace - 8:00:15 PM] Received response 'textDocument/diagnostic - (15627)' in 1ms.
[Trace - 8:00:15 PM] Sending request 'completionItem/resolve - (15628)'.
[Trace - 8:00:15 PM] Received response 'completionItem/resolve - (15628)' in 0ms.
[Trace - 8:00:15 PM] Sending request 'textDocument/semanticTokens/full - (15629)'.
[Trace - 8:00:15 PM] Received response 'textDocument/semanticTokens/full - (15629)' in 3ms.
[Trace - 8:00:16 PM] Sending request 'textDocument/definition - (15630)'.
[Trace - 8:00:16 PM] Received response 'textDocument/definition - (15630)' in 1ms.
[Trace - 8:00:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:17 PM] Sending request 'textDocument/diagnostic - (15631)'.
🔬 Inspect "file:///g%3A/kex/quake2ex/kex3_ptah/source/game/as/scripts/game/ctf.as"
[Trace - 8:00:17 PM] Received request 'workspace/diagnostic/refresh - (4073)'.
[Trace - 8:00:17 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:17 PM] Sending response 'workspace/diagnostic/refresh - (4073)'. Processing request took 0ms
[Trace - 8:00:17 PM] Sending request 'textDocument/diagnostic - (15632)'.
[Trace - 8:00:17 PM] Sending request 'textDocument/diagnostic - (15633)'.
[Trace - 8:00:17 PM] Received response 'textDocument/diagnostic - (15631)' in 17ms.
[Trace - 8:00:17 PM] Sending request 'textDocument/diagnostic - (15634)'.
[Trace - 8:00:17 PM] Received response 'textDocument/diagnostic - (15632)' in 3ms.
[Trace - 8:00:17 PM] Received response 'textDocument/diagnostic - (15633)' in 3ms.
[Trace - 8:00:17 PM] Received response 'textDocument/diagnostic - (15634)' in 1ms.
[Trace - 8:00:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:17 PM] Sending request 'textDocument/diagnostic - (15635)'.
🧹 Clean inspected results
🔬 Inspect "file:///g%3A/kex/quake2ex/kex3_ptah/source/game/as/scripts/as.predefined"
🔬 Inspect "file:///g%3A/kex/quake2ex/kex3_ptah/source/game/as/scripts/game/ctf.as"
[Trace - 8:00:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:17 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:17 PM] Sending request 'textDocument/semanticTokens/full - (15636)'.
[Trace - 8:00:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:17 PM] Sending request 'textDocument/completion - (15637)'.
[Trace - 8:00:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:17 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:18 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:18 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:18 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:18 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:18 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:18 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:18 PM] Sending request 'textDocument/signatureHelp - (15638)'.
[Trace - 8:00:18 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:18 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:18 PM] Sending request 'textDocument/signatureHelp - (15639)'.
[Trace - 8:00:18 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:19 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:19 PM] Sending request 'textDocument/signatureHelp - (15640)'.
[Trace - 8:00:19 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:19 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:19 PM] Sending request 'textDocument/signatureHelp - (15641)'.
[Trace - 8:00:19 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:19 PM] Sending request 'textDocument/signatureHelp - (15642)'.
[Trace - 8:00:20 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:20 PM] Sending request 'textDocument/signatureHelp - (15643)'.
[Trace - 8:00:20 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:20 PM] Sending request 'textDocument/signatureHelp - (15644)'.
[Trace - 8:00:20 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:20 PM] Sending request 'textDocument/signatureHelp - (15645)'.
[Trace - 8:00:20 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:20 PM] Sending request 'textDocument/signatureHelp - (15646)'.
[Trace - 8:00:21 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:21 PM] Sending request 'textDocument/signatureHelp - (15647)'.
[Trace - 8:00:21 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:21 PM] Sending request 'textDocument/signatureHelp - (15648)'.
[Trace - 8:00:21 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:21 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:21 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:21 PM] Sending request 'textDocument/signatureHelp - (15649)'.
[Trace - 8:00:21 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:21 PM] Sending request 'textDocument/signatureHelp - (15650)'.
[Trace - 8:00:21 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:22 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:22 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:22 PM] Sending request 'textDocument/signatureHelp - (15651)'.
[Trace - 8:00:22 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:22 PM] Sending request 'textDocument/signatureHelp - (15652)'.
[Trace - 8:00:22 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:22 PM] Sending request 'textDocument/signatureHelp - (15653)'.
[Trace - 8:00:22 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:23 PM] Sending request 'textDocument/completion - (15654)'.
[Trace - 8:00:23 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:23 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:23 PM] Sending request 'textDocument/signatureHelp - (15655)'.
[Trace - 8:00:23 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:23 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:23 PM] Sending request 'textDocument/signatureHelp - (15656)'.
[Trace - 8:00:23 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:23 PM] Sending request 'textDocument/signatureHelp - (15657)'.
[Trace - 8:00:23 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:23 PM] Sending request 'textDocument/signatureHelp - (15658)'.
[Trace - 8:00:24 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:24 PM] Sending request 'textDocument/signatureHelp - (15659)'.
[Trace - 8:00:24 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:24 PM] Sending request 'textDocument/signatureHelp - (15660)'.
[Trace - 8:00:24 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:24 PM] Sending request 'textDocument/signatureHelp - (15661)'.
[Trace - 8:00:32 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:32 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:32 PM] Sending request 'textDocument/signatureHelp - (15662)'.
[Trace - 8:00:32 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:32 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:32 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:32 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:32 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:32 PM] Sending request 'textDocument/signatureHelp - (15663)'.
[Trace - 8:00:33 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:33 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:33 PM] Sending request 'textDocument/signatureHelp - (15664)'.
[Trace - 8:00:33 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:33 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:33 PM] Sending request 'textDocument/signatureHelp - (15665)'.
[Trace - 8:00:33 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:33 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:33 PM] Sending request 'textDocument/signatureHelp - (15666)'.
[Trace - 8:00:33 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:33 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:33 PM] Sending request 'textDocument/signatureHelp - (15667)'.
[Trace - 8:00:33 PM] Sending notification 'textDocument/didChange'.
[Trace - 8:00:34 PM] Sending notification '$/cancelRequest'.
[Trace - 8:00:34 PM] Sending request 'textDocument/signatureHelp - (15668)'.
[Trace - 8:00:35 PM] Sending notification 'textDocument/didSave'.
[Trace - 8:00:36 PM] Sending notification '$/cancelRequest'.
```

**Comment by Paril** [comment]
OK I got a verbose trace. The final interesting message is this one:

```
ðŸ”¬ Inspect "file:///g%3A/kex/quake2ex/kex3_ptah/source/game/as/scripts/game/ctf.as"
Inspector | Tokenizer       : 3.6508000000030734 ms
Inspector | Preprocess      : 1.1013000000093598 ms
```

After that, all that is in the log is various `Sending request/notification` messages; comparing to prior Inspect calls, it never reaches Parser or Analyzer, so something inside of Parser is probably infinite looping?

**Comment by Paril** [comment]
Found it! It's in `parseExprPostOp2`. Specifically, this loop:

```ts
    const indexerList: ParsedPostIndexer[] = [];
    while (parser.isEnd() === false) {
        const identifier = parseIdentifierWithColon(parser);

        const assign = expectAssign(parser);
        if (assign !== undefined) indexerList.push({identifier: identifier, assign: assign});

        if (expectContinuousOrClose(parser, ',', ']', indexerList.length > 0) === BreakOrThrough.Break) break;
    }
```

`identifier` is undefined, and it just keeps looping because the final thing that happens is it gets rewound to before the assignment.

I narrowed down the line that caused it, too:

`other.e.angles[ = 0;`

I was converting some code from cpp to AS and since it tries to inspect on every single character it eventually landed on this combination of code that caused it to spin forever

**Comment by sashi0034** [comment]
I see, that makes sense! Thanks for the report, that was helpful.

I'll review the parser code this week while cleaning it up, as there may be similar bugs elsewhere.

**Comment by sashi0034** [comment]
I’ve updated to a new version today!
In this version, I've made significant improvements to the inspector and analyzer, so performance should be much better.

In my environment, the latest version has garbage collection working properly, and it seems to have resolved the previous memory leak issues.

If the memory leak issue also looks resolved on your end, I’ll go ahead and close this issue. thanks!

**Comment by Paril** [comment]
It's really hard to tell tbh because there's several other issues that currently prevent my project from being properly parsed, and a lot of the files either stop parsing early or don't parse at all. I can't really be confident that it's fully solved until the extension can parse every file into the project (most of the files can't 'see' the types in other files, despite Implicit Include being enabled). I can pack up a newer version if you want to see what I'm trying to work with (it uses subfolders).

I think there might also still be an issue with Implicit Include getting stuck in an infinite loop since each file includes every other file and it recursively just keeps trying to inspect each other, but I've not yet tracked that one down.

**Comment by sashi0034** [comment]
That sounds like a serious issue. I'm really curious to see where the infinite loop is happening. If you'd like, I’d be happy to take a look at your project files.

**Comment by Paril** [comment]
[scripts.zip](https://github.com/user-attachments/files/19078356/scripts.zip) Here's the latest set; there's some mid-conversion code in `target.as`. I've had the extension lock up a couple of times still when doing conversions, I'll have to pull & attach a debugger again to get you more info. The version from 2-22 still has the `[` infinite loop as well, I assume that was fixed in main but just not uploaded to the store yet.

In order of importance, here's the problems that make it hard to fully test:
- files in other folders seem to be ignored, but it's not consistent. Sometimes `edict.as` will get parsed and let me see `ASEntity` with another file open, sometimes it won't.
- `= void` is not handled properly which breaks function parsing
- features from WIP branch (foreach, template functions, etc)
- features that I've submitted to Andreas for inclusion in WIP (nodiscard)

**Comment by sashi0034** [comment]
Thanks for getting back so quickly! I’ll check it out.

**Comment by Paril** [comment]
I saw an update made today - I pulled and it seems to have fixed subfolders, at least. I did get it to freeze, but I didn't have a debugger running at the time, oops. I have one attached now, will post a stack trace when I get one.

**Comment by Paril** [comment]
OK, I'm still digging a bit through this, but I think the problem has to do with `reanalyzeFilesWithDependency`. I'm trying to follow all of the logic, I don't really understand how it manages to avoid always being stuck in an infinite loop (sometimes it only processes the current file and nothing else), but at least in the trace I have here, I modified one file with typing and then it put all 94 files into the `_reanalysisQueue`. It pops them off for analysis, but it seems like they are just bouncing back & forth between `_analysisQueue` and `_reanalysisQueue`. Once any file gets analyzed, since every file includes every other file (because of implicit inclusion), it just keeps the queue going until the service eventually kills itself.

**Comment by sashi0034** [comment]
Oh, I see - so the issue still isn't fully resolved. :( Anyway, thanks for the thorough investigation. I’ll try to reproduce the same behavior on my end and see if I can confirm it.

In future versions, it might be a good idea to compare edit diffs before deciding whether to trigger a reanalysis. But for now,  this month I’d like to focus on fixing the many existing bugs in the analyzer, and then look into optimizing this part afterward.

**Comment by Paril** [comment]
Another interesting thing is that it seems to parse the entire codebase three times total just by reloading the window.
https://streamable.com/1ym887

I think it's because it starts a parse from opening the folder, then it receives a configurationChanged from settings loaded (asynchronously?), and then the third one I have no idea, heh.

**Comment by sashi0034** [comment]
Today, I discovered a bug that was directly causing a memory leak 🥲(The issue was in the scope inclusion process: [#151
](https://github.com/sashi0034/angel-lsp/commit/4cca1c4a3ee4f131b8b6e7f3374b4acda68746a4) ).

I haven't done detailed profiling yet, but memory usage looks dropped significantly, and the hoisting process has become much faster.

Looking ahead, I plan to further improve the module reanalysis algorithm. Specifically, when a file is edited, I'll make it so that other files are not re-inspected if the change is within the local scope. Only when the global scope is modified will other files be re-inspected.

**Comment by Paril** [comment]
Cool, I'll monitor and see.

The other note makes sense & should improve performance massively.

**Comment by sashi0034** [comment]
Today, I implemented the feature I mentioned earlier—only analyzing other files when editing outside of an anonymous scope!

**Comment by Paril** [comment]
Sweet! I've been playing with it the past day or so, and I haven't experienced any crashes or memory issues. I've not been paying close attention to mem usage but from the few times I checked, it stayed below 900 MB or so.

The only issue I've experienced is one that isn't new, but is more obvious now that the extension doesn't crash after ~30 mins; rarely, it seems to think two types are not identical any more.

![](https://i.imgur.com/SJKbZr7.png)
![](https://i.imgur.com/N4uT930.png)

I don't know exactly what causes this. Doing Ctrl+Shift+P > Reload Window often fixes it, but there's definitely still an issue with the analyzer there. I notice when I reload the window, it will often show 6k+ problems, and it slowly whittles it down to under 300 or so as files get analyzed, but the particular bug I run into is after editing and re-opening files it sometimes shows the behavior above.

**Comment by sashi0034** [comment]
Ah, I suspect this issue is related to the fact that I set the analysis frequency for closed files to a slow 0.5 seconds. As a result, some files may have ended up going unanalyzed for a long time, which could be causing problems all over the place. (It was foolish of me not to take this into account before implementing it 🥲)

Since I implemented the behavior where other files aren't analyzed while edits are happening in an anonymous scope, it might be time to revisit the approach of analyzing closed files at a slower pace.

**Comment by Paril** [comment]
Ahh, okay.

Yeah it seems to think that the types are like.. blank/placeholder types. Just as an example:
![](https://i.imgur.com/Dv5BpyS.png)
`e` and `client` are members of `ASEntity`. In the analyzers' current state, it doesn't know that these exist.
If I simply delete and re-type the `.`, the problems go away and the correct data is visible:
![](https://i.imgur.com/q599gWQ.png)
It instantly fixes when I hit a key, so I wonder if it's just holding onto prior Problems or something?

**Comment by Paril** [comment]
I think we can safely close this bug for now, the memory issues seem to be mostly resolved and I haven't had the extension crash in a long time. If it comes back we can re-open it.
